[package]
name = "spike-redb-quick-repair"
version = "0.1.0"
edition = "2024"

[dependencies]
redb = "2.6.3"
rand = "0.9"
argh = "0.1.13"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
